### ISSUE TITLE
There is now an official Korners bug fix in master

### ISSUE THREAD

**Issue by ryu-ketsueki** [paulmcauley/classik#19]
I noticed there was a warning about rounding corners with the window decoration of ClassiK, saying it would bring in the Korners bug. But now that it has been fixed, requiring only a mask to tell which parts to blur, all that is necessary to do is implement this on ClassiK. It's still not on Plasma yet, being promised to come out on 5.25 but you could start working on it so it's ready by the time this release comes out

**Comment by paulmcauley** [comment]
Yes, it may take some time to get right.

In the meantime, there actually has been a kornerbug regression introduced by recent point releases Plasma 5.24 which I am trying to get checked at https://bugs.kde.org/show_bug.cgi?id=451778 . ClassiK defaults did not have this problem in 5.23 (and I think the initial 5.24 build) but now does :(

**Comment by paulmcauley** [comment]
I have implemented an update using the new 5.25 setBlurRegion API on the kornerbug-fix-plasma5.25 branch at https://github.com/paulmcauley/classik/tree/kornerbug-fix-plasma5.25

Testing is welcome :D

It looks pretty good on X11, though on Wayland when blur is on, the blur region looks a bit rough and pixelated/aliased (I think this is a kwin issue). I also observed an issue with corner/edge snapping a window but that seems to be because these events do not emit a signal to inform me to update the blur region - investigating.

I defined the blur region using:`
setBlurRegion( QRegion( m_windowPath->toFillPolygon().toPolygon()) ) ;`
This is because I construct the window shape using a QPainterPath and then convert it to a QRegion needed by the new API. Performance seems OK to me, but I'm not sure if this is the most efficient -- David Edmundson had mentioned a method about getting a mask from a QPixmap, but I could not see how to do that in the window decoration. If anyone has any insight then let me know.

**Comment by Sojiro84** [comment]
> I have implemented an update using the new 5.25 setBlurRegion API on the kornerbug-fix-plasma5.25 branch at https://github.com/paulmcauley/classik/tree/kornerbug-fix-plasma5.25
> 
> Testing is welcome :D
> 

I tried installing your linked version but I get this error:

```
[ 15%] Building CXX object kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o
/home/sojiro/Downloads/classik-kornerbug-fix-plasma5.25/kdecoration/breezedecoration.cpp: In member function ‘void Breeze::Decoration::updateOpaqueAndBlur(bool)’:
/home/sojiro/Downloads/classik-kornerbug-fix-plasma5.25/kdecoration/breezedecoration.cpp:1293:13: error: ‘setBlurRegion’ was not declared in this scope
1293 |             setBlurRegion( QRegion() );
|             ^~~~~~~~~~~~~
/home/sojiro/Downloads/classik-kornerbug-fix-plasma5.25/kdecoration/breezedecoration.cpp:1299:17: error: ‘setBlurRegion’ was not declared in this scope
1299 |                 setBlurRegion( QRegion( m_windowPath->toFillPolygon().toPolygon()) ) ;
|                 ^~~~~~~~~~~~~
/home/sojiro/Downloads/classik-kornerbug-fix-plasma5.25/kdecoration/breezedecoration.cpp:1300:20: error: ‘setBlurRegion’ was not declared in this scope
1300 |             } else setBlurRegion( QRegion() );
|                    ^~~~~~~~~~~~~
make[2]: *** [kdecoration/CMakeFiles/classikdecoration.dir/build.make:131: kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: kdecoration/CMakeFiles/classikdecoration.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by paulmcauley** [comment]
> 

What Plasma version are you running? You need to be running a recent 5.24.80 development build of Plasma to test. This is because the new API (i.e. the setBlurRegion()  method) has not been officially released yet and is scheduled for Plasma 5.25.

I was thinking about using a SFINAE templating technique to detect first if setBlurRegion exists but this seems like a lot of effort and complexity...

**Comment by Sojiro84** [comment]
> > 
> 
> What Plasma version are you running?

That explains it. I am on 5.24.4.

I shall have to wait for the june release then. ^-^

**Comment by ryu-ketsueki** [comment]
Any work on implementing the API on Wayland? I still have the Korners here on my end

**Comment by paulmcauley** [comment]
> Any work on implementing the API on Wayland? I still have the Korners here on my end

The API calls in this branch are already implemented for both X11 and Wayland so I'm not sure what you mean. Maybe you need to restart and toggle window decorations? On Wayland you should just get a slightly rougher blur region, but it should still look better than the previous korners. 

The roughness of the curves in Wayland seems to be something to do with the Plasma/Kwin implementation - I intend to report a bug.

**Comment by ryu-ketsueki** [comment]
Then there must be something wrong happening because I am getting sharp black corners sometimes and sometimes they are tinted after the window color

**Comment by paulmcauley** [comment]
Well here is Wayland with no transparency (no black corners are visible to me):
![no_blur_wayland](https://user-images.githubusercontent.com/6924479/166105585-930e0406-583e-4114-8eef-8de69363fce7.png)

The next screenshot is probably the worst you are going to get on Wayland. Here transparency and blur is turned on, and shadows are turned off to highlight the blockyness of the new blur region on Wayland:
![rough_blur_region_wayland](https://user-images.githubusercontent.com/6924479/166105758-7834c300-3491-4c42-8682-f8963f3ab334.png)

This blockiness I am going to report as a kwin bug.

**Comment by ryu-ketsueki** [comment]
I found what went wrong. I was missing to do git checkout so I was still on master. My bad. Now I don't have black corners

**Comment by paulmcauley** [comment]
Updated the branch to call the setBlur method less frequently, and fix a bug with full-screen blurred titlebars.

**Comment by ryu-ketsueki** [comment]
So if the fix is already on master, should we close this issue?

**Comment by Sojiro84** [comment]
Just installed 5.24.90 beta that released yesterday and when compiling I get this error:

```
error: variable ‘std::array<const char*, 1> exceptionClassNames’ has initializer but incomplete type
2749 |             std::array<const char*,1> exceptionClassNames = {"KateScrollBar"};
|                                       ^~~~~~~~~~~~~~~~~~~
```

**Comment by paulmcauley** [comment]
> Just installed 5.24.90 beta that released yesterday and when compiling I get this error:
> 
> ```
> error: variable ‘std::array<const char*, 1> exceptionClassNames’ has initializer but incomplete type
> 2749 |             std::array<const char*,1> exceptionClassNames = {"KateScrollBar"};
> |                                       ^~~~~~~~~~~~~~~~~~~
> ```

This has nothing to do with this Kornerbug issue. Please could you give some more details in #27? Thanks

**Comment by paulmcauley** [comment]
> So if the fix is already on master, should we close this issue?

I'm leaving it open for now, as I'm seeing differences between what I am seeing in the 5.24.90 beta and what I tested on the Plasma git version a few weeks ago.

For a start, I am not getting any blur at all on the 5.24.90 beta.

**Comment by paulmcauley** [comment]
> For a start, I am not getting any blur at all on the 5.24.90 beta. See https://bugs.kde.org/show_bug.cgi?id=454453

The latest 5.24.90 builds fix this blur issue
